test:
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_PORT_5432_TCP_ADDR") %>
  port: <%= ENV.fetch("POSTGRES_PORT_5432_TCP_PORT") %>
  encoding: unicode
  database: willing_quiz_test
  username: myuser
  password: ourlittlesecret
