// @flow

const NO_ANSWER = '回答しない';
const ANSWERS = [
  '非常にあてはまる',
  'あてはまる',
  'ややあてはまる',
  'どちらともいえない',
  'ややあてはまらない',
  'あてはまらない',
  '全くあてはまらない',
  NO_ANSWER,
];

export const SURVEY_DATA_1 = [
  { question: '自分が注目されるとうれしい。', answers: ANSWERS },
  { question: '物事をすすめるとき，うまくいったときのことを，よく想像する。', answers: ANSWERS },
  { question: 'だれかにきらわれるのがこわい。', answers: ANSWERS },
  { question: '勝負するなら絶対に負けたくない。', answers: ANSWERS },
  { question: '生まれ持った自分の頭のよさは，努力すればもっと良くできる。', answers: ANSWERS },
  { question: 'とちゅうであきらめることは，きらいだ。', answers: ANSWERS },
  { question: 'だれかと話をするのが好きだ。', answers: ANSWERS },
  { question: '何事にもまじめに取り組むタイプだ。', answers: ANSWERS },
  { question: '頭が悪いと思われないように，もっと学習をしたいと思う。', answers: ANSWERS },
  { question: 'やりたいと思ったことは，すぐに取りかかる。', answers: ANSWERS },
  { question: '上手くいくかどうかよりも，失敗しないかどうかの方が気になる。', answers: ANSWERS },
  { question: '競争はきらいだ。', answers: ANSWERS },
  { question: 'いつだってみんなから注目されていたい。', answers: ANSWERS },
  { question: '自分はダメな人間だと思うことがよくある。', answers: ANSWERS },
  { question: '他の人が自分のことをうわさしていると，とても気になる。', answers: ANSWERS },
  { question: 'あきっぽいほうだ。', answers: ANSWERS },
  { question: 'いつまでに何を学ぶか，計画を立てて学習をしている。', answers: ANSWERS },
  { question: '欲しいものを手に入れるために努力しようと思う。', answers: ANSWERS },
  { question: 'テストや他人から評価を受けるとき，失敗したらどうしようと，よく考える。', answers: ANSWERS },
  { question: '長期的に役に立つ勉強をしたい。', answers: ANSWERS },
  { question: '自分の頭のよさは，勉強してもよくならないと，あきらめている。', answers: ANSWERS },
  { question: '自分のことは自分で決めたい。', answers: ANSWERS },
  { question: 'みんなで協力すると，一人でやるときよりも上手くいく。', answers: ANSWERS },
  { question: '重要なことは，自分で決めるよりも，信用できるだれかに決めてもらいたい。', answers: ANSWERS },
  { question: '自分の力をのばすために，学習をしたいと思う。', answers: ANSWERS },
  { question: '競争することで，自分の能力を高められる。', answers: ANSWERS },
  { question: '学習において，今まであまり良い結果が得られたことがない。', answers: ANSWERS },
  { question: '自分しだいで，思いえがいた未来を実現することができると思う。', answers: ANSWERS },
  { question: 'だれとも協力しなくても成果を出せる人間が，世の中にいると思う。', answers: ANSWERS },
  { question: 'テストの結果や，まわりの人からの評価をよくするために，学習したいと思う。', answers: ANSWERS },
  { question: '人を見下したことはない。', answers: ANSWERS },
  { question: '何かを学んだときは，うまく学べなかったことのほうが多いと思う。', answers: ANSWERS },
  { question: 'まわりの人よりも悪い結果を出さないように，きちんと学びたい。', answers: ANSWERS },
  { question: '学習するときは，目標を立てて，それを目指して努力する。', answers: ANSWERS },
  { question: '他の人がやるかどうか迷っていることでも、自分からやるほうだ。', answers: ANSWERS },
  { question: 'みんなでいっしょに作業をするのは，楽しい。', answers: ANSWERS },
  { question: 'やる気を出すために，競争することがある。', answers: ANSWERS },
  { question: 'いくら勉強をしても，自分の知能の高さは変わらない。', answers: ANSWERS },
  { question: '将来役に立つことは，今役にたたなくても，学びたいと思う。', answers: ANSWERS },
  { question: '自分が目立つチャンスがあれば，目立ちたい。', answers: ANSWERS },
  { question: '自分がきらわれているのではないかと，不安になる。', answers: ANSWERS },
  { question: '何かにチャレンジするとき，成功をイメージすることが多い。', answers: ANSWERS },
  { question: '勉強すればするほど，自分の知能は高くなると信じている。', answers: ANSWERS },
  { question: '友達をバカにしたことがある。', answers: ANSWERS },
  { question: '新しいことを覚えたり，知識を増やすために，もっと学びたいと思う。', answers: ANSWERS },
  { question: 'まわりの人にどう思われているか，気になる。', answers: ANSWERS },
  { question: 'うまくいったときのことを想像しながら，物事をすすめるようにしている。', answers: ANSWERS },
  { question: 'がんばれば，夢はかなうと信じている。', answers: ANSWERS },
  { question: '他の人に全てを決めてもらうほうが，安心できる。', answers: ANSWERS },
  { question: '私はどちらかというと落ちこぼれだ。', answers: ANSWERS },
  { question: '何をするか自分で決めたほうが気分が良い。', answers: ANSWERS },
  { question: '自分で決めたことは，最後までやりとげたい。', answers: ANSWERS },
  { question: '協力して仕事をしなくても，力がある人はひとりでできると思う。', answers: ANSWERS },
  { question: '人と会うことが楽しい。', answers: ANSWERS },
  { question: '熱しやすく冷めやすい。', answers: ANSWERS },
  { question: '何かを学ぶときに，うまくいかなかったらどうしよう，とよく考える。', answers: ANSWERS },
  { question: '何かを学ぶときは，他の人よりも良い成績や高い評価を取りたいと思う。', answers: ANSWERS },
  { question: '機会があれば，みんなに自分の得意なことをアピールしたい。', answers: ANSWERS },
  { question: 'テストや評価を受けるとき，悪い結果にならないか心配になる。', answers: ANSWERS },
  { question: 'やると決めたら，最後までやり通す。', answers: ANSWERS },
  { question: 'できれば競争したくない。', answers: ANSWERS },
  { question: '負けたくないと思う気持ちが強い。', answers: ANSWERS },
  { question: '難しいことがあっても，あきらめないほうだ。', answers: ANSWERS },
  { question: '人が集まったとき，他の人より目立ちたいと思う。', answers: ANSWERS },
  { question: '何かを任されたとき，できないかもしれないと不安になることが多い。', answers: ANSWERS },
  { question: 'つまらないことでも，他の人と競争すれば，おもしろくなる。', answers: ANSWERS },
  { question: 'あなたの性別をお答えください。', answers: ['男性', '女性', 'その他', NO_ANSWER] },
  {
    question: 'あなたの年齢をお答えください',
    answers: [
      '15歳以下',
      '16歳～18歳',
      '19歳～22歳',
      '23歳～29歳',
      '30歳～39歳',
      '40歳～49歳',
      '50歳～59歳',
      '60歳以上',
      NO_ANSWER,
    ],
  },
];

export const SURVEY_DATA_2 = [
  {
    question: 'このアプリケーションを利用してみてどうでしたか。',
    answers: ['とてもよかった', 'よかった', 'どちらともいえない', 'よくなかった', '非常によくなかった'],
  },
  {
    question: 'このアプリケーションを今後も利用したいと思いますか。',
    answers: ['利用したい', '少し利用したい', 'どちらともいえない', 'あまり利用したくない', '利用したくない'],
  },
  { question: 'このアプリケーションの良かった点はどこですか。' },
  { question: 'このアプリケーションの改善してほしい点はどこですか。' },
  {
    question:
      'このアプリケーション以外で、「やる気が上がる」という観点で、良かったと感じたアプリケーションがあれば、ご回答下さい。',
  },
];
